### PR TITLE
MVP - Junkership/Trashbot Collisions

### LINKED ISSUE #13: Junkership and Trashbots can collide.
Using rectangular collision, or AABB collision. Eventually, we might want to investigate in making the hitbox of the junkership a bit smaller.

### LINKED ISSUE #14: Junkership despawn when they collide with Trashbots.

### LINKED ISSUE #15: Junkership can respawn if it's been despawned.
If no junkership exists, wait for any arrow key or space bar to be hit to spawn a new junkership. Be sure this junkership has a new score of just zero.

### LINKED ISSUE #23: Game crashes if a Trashbot dies while multiple Projectiles are on screen
Caused by collision logic checking already destroyed (null) Objects

### PR DESCRIPTION
**Pull request by Phyoog**
Closes #13, closes #14, closes #15: Junkerships collide with Trashbots, die, and trigger game over logic which currently simply respawns them.

Fixes #23: Trashbot was continuing to iterate through game.children after it died, leading to comparing itself (now null) to the other projectiles. Added null check to hasCollision and moved actual "death" of a Trashbot to outside the collision checking loop.

Playable build at http://mocsarcade.github.io/starjunk/v0.1.5/

### CODE REVIEW

File: source/Trashbot.js [hunk 1]
```diff
@@ -18,14 +19,22 @@ export default class Trashbot extends Pixi.Sprite {
         if (this.position.x + this.width < 0) {
             this.position.x = Reference.GAME_WIDTH
         }
+        var killedBy
```
Comment (ehgoodenough) [inline source/Trashbot.js]: Oh! A lonely unused variable. :(

Poor variable.

File: source/Utility.js [hunk 2]
```diff
@@ -1,18 +1,22 @@
...
-    && y1 < y2 + h2 && h1 + y1 > y2) {
-        return true
-    } else {
-        return false
+        if(x1 < x2 + w2 && x1 + w1 > x2
+        && y1 < y2 + h2 && h1 + y1 > y2) {
+            return true
+        } else {
+            return false
+        }
```
Comment (ehgoodenough) [inline source/Utility.js:20]: It's really just an architecture preference, but what if we made an abstract superclass, named `Entity`, where we could put shared code? `Entity` would inherit from `Pixi.Sprite`, and `Junkership`/`Trashbot`/`Projectile` would all inherit from `Entity.` Our functions like `hasCollision`, and eventually functions for particles, controllers/inputs, and statics could be shared here.

Thoughts?

File: source/index.js [hunk 3]
```diff
@@ -21,5 +22,13 @@ var loop = new Afloop(function(delta) {
...
+    if (game.playerCount === 0) {
+        gameOver()
+    }
     renderer.render(game)
 })
+
+var gameOver = function () {
+    console.log("Respawning Junkership")
+    game.addChild(new Junkership())
+}
```
Comment (ehgoodenough) [inline source/index.js:34]: I think `gameOver` could possibly be a method of `game`.

File: source/index.js [hunk 4]
```diff
@@ -13,6 +13,7 @@ renderer.roundPixels = true
 
 document.getElementById("mount").appendChild(renderer.view)
 window.game = new Pixi.Container()
+game.playerCount = 0
 game.addChild(new Junkership())
```
Comment (ehgoodenough) [inline source/index.js:17]: You'll eventually want to subclass something from `Pixi.Container`, especially since we're already adding so much logic it. You can do all sorts of nifty things, like add overrides for `.addChild` and `.removeChild` such that they sorted by class or position or whatever. But more pressingly, you can add stuff like `this.playerCount = 0` to the constructor of your class.

File: source/index.js [hunk 5]
```diff
@@ -21,5 +22,13 @@ var loop = new Afloop(function(delta) {
     game.children.forEach((child) => {
         child.update(delta)
     })
+    if (game.playerCount === 0) {
```
Comment (ehgoodenough) [inline source/index.js]: Ha! Way to use triple equality. If you hadn't, javascript would parse anything "falsy" to be equal to zero, because javascript is weeeeird.

File: source/Trashbot.js [hunk 6]
```diff
@@ -18,14 +19,22 @@ export default class Trashbot extends Pixi.Sprite {
...
         game.children.forEach((toCompare) => {
```
Comment (ehgoodenough) [inline source/Trashbot.js]: #imo:

I find `toCompare` a confusing variable name. Maybe `game.children.forEach((child))`? Or maybe `entity`?

**Comment by ehgoodenough** [comment]
We're get very close to an MVP! **:D**

[selfie-5](https://github.com/thieman/github-selfies/)

File: source/Utility.js (hunk 2 above)
Comment (Phyoog) [inline source/Utility.js:20]: We could, but there won't be much shared code, honestly. hasCollision could go there, sure... but controllers and inputs are going to only apply to Junkerships (and are probably going to need a class of their own once the time comes for multiplayer support) and statics can reside in Reference or Utility as appropriate. As for particles, we've got the explosion effect, but I imagine we're going to want the Junkership deaths to be a bit more dramatic than the Trashbot explosions. The parallax effect starfield doesn't behave like the other Entities, so they wouldn't be appropriate for tying to this either. Are there other particle effects you had in mind?

If Javascript had something more akin to an Interface, I'd say go with it, but nearly everything we need is in Pixi.Sprite anyway. Seems overkill to add an abstract class (which looks to be a bit clunky in Javascript, though a bit better in ES6) for what is going to mostly get overridden.

File: source/index.js (hunk 3 above)
Comment (Phyoog) [inline source/index.js:34]: Makes sense. Changed in next commit.

File: source/index.js (hunk 5 above)
Comment (Binome) [inline source/index.js]: == != ===

File: source/index.js (hunk 4 above)
Comment (Phyoog) [inline source/index.js:17]: That'll work. I think maybe we could push it out to it's own file. As more stuff gets piled into it, it'll help keep index.js readable. I'll start pulling that out.

File: source/Trashbot.js (hunk 6 above)
Comment (Phyoog) [inline source/Trashbot.js]: Changed. Went with "child"

Also got rid of those unnecessary comment slashes.

File: source/index.js (hunk 4 above)
Comment (Phyoog) [inline source/index.js:17]: Thought... we could pull collisionCheck from Utility and put it in this new GameContainer class. Makes sense that it's the "game" that's checking for collisions. Looking within itself, as it were. Cuts down on the number of files.

Opinions?

**Comment by Phyoog** [comment]
Commit pushed with the latter items. Build at https://mocsarcade.github.io/starjunk/v0.1.5 updated.
